-- Add rarity and demand columns to items table
ALTER TABLE items 
ADD COLUMN IF NOT EXISTS rarity TEXT,
ADD COLUMN IF NOT EXISTS demand TEXT,
ADD COLUMN IF NOT EXISTS value_fr DECIMAL,
ADD COLUMN IF NOT EXISTS value_f DECIMAL,
ADD COLUMN IF NOT EXISTS value_r DECIMAL,
ADD COLUMN IF NOT EXISTS value_h DECIMAL,
ADD COLUMN IF NOT EXISTS value_nfr DECIMAL,
ADD COLUMN IF NOT EXISTS value_np DECIMAL,
ADD COLUMN IF NOT EXISTS value_nr DECIMAL,
ADD COLUMN IF NOT EXISTS value_n DECIMAL,
ADD COLUMN IF NOT EXISTS value_mfr DECIMAL,
ADD COLUMN IF NOT EXISTS value_mf DECIMAL,
ADD COLUMN IF NOT EXISTS value_mr DECIMAL,
ADD COLUMN IF NOT EXISTS value_m DECIMAL;
